fixtures:
  repositories:
    "augeasproviders_core": "https://github.com/hercules-team/augeasproviders_core.git"
    "augeasproviders_sysctl": "https://github.com/hercules-team/augeasproviders_sysctl.git"
    "portmap": "https://github.com/jbeard6/jbeard-portmap.git"
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib.git"

  symlinks:
    "bootparamd": "#{source_dir}"
