name 'buzzdeee-bootparamd'
version '0.1.0'
source 'https://github.com/buzzdeee/buzzdeee-bootparamd.git'
author 'buzzdeee'
license 'Apache 2.0'
summary 'Puppet Module to manage bootparamd'
description 'Puppet Module to manage bootparamd'
project_page 'https://github.com/buzzdeee/buzzdeee-bootparamd'
dependency 'puppetlabs/concat', '>= 1.1.0'
